### ISSUE TITLE
Score recognition bug

### ISSUE THREAD

**Issue by louis030195** [louis030195/xmoto-gym#13]
https://github.com/louis030195/xmoto-gym/blob/2f2ca31662564cf6c4fdea96ca96156e047ed7b3/image_preprocessor.py#L97

> Traceback (most recent call last):
>   File "example.py", line 6, in <module>
>     env.step(env.action_space.sample()) # take a random action
>   File "/mnt/sdb/ML/xmoto-gym/gym_xmoto/envs/xmoto_env.py", line 128, in step
>     score = recognize_score(tmpState[1][0:0+30,100:100+30])
>   File "/mnt/sdb/ML/xmoto-gym/score_recognition.py", line 23, in recognize_score
>     score_digits = preprocess_image(image)
>   File "/mnt/sdb/ML/xmoto-gym/image_preprocessor.py", line 97, in preprocess_image
>     for contour in contours:
> TypeError: 'NoneType' object is not iterable

**Comment by rom1504** [comment]
what does `imutils.is_cv2()` return in your environment ?
